runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /tables-from-db
  script: unused
  login: optional
  secure: optional
- url: /data-from-db
  script: unused
  login: optional
  secure: optional
- url: /example-db
  script: unused
  login: optional
  secure: optional
- url: /filters
  script: unused
  login: optional
  secure: optional
- url: /databases
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
